---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	retrieve(retrieve)
	rerank(rerank)
	generate(generate)
	decide_web(decide_web)
	web_retrieve(web_retrieve)
	merge_contexts(merge_contexts)
	finalize_contexts(finalize_contexts)
	rewrite(rewrite)
	abstain_response(abstain_response)
	ground(ground)
	__end__([<p>__end__</p>]):::last
	__start__ --> rewrite;
	abstain_response --> ground;
	decide_web -. &nbsp;answer&nbsp; .-> finalize_contexts;
	decide_web -. &nbsp;web&nbsp; .-> web_retrieve;
	finalize_contexts -. &nbsp;abstain&nbsp; .-> abstain_response;
	finalize_contexts -. &nbsp;answer&nbsp; .-> generate;
	generate --> ground;
	merge_contexts --> finalize_contexts;
	rerank --> decide_web;
	retrieve --> rerank;
	rewrite --> retrieve;
	web_retrieve --> merge_contexts;
	ground --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
